name: client
description: The plgd.dev mobile client for onboarding of OCF enabled devices.
version: 1.0.1+6

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.5.7
  flutter_inappwebview: ^4.0.0+4
  shared_preferences: ^0.5.10
  http: ^0.12.2
  jwt_decoder: ^1.0.3
  flutter_spinkit: ^4.1.2+1
  flushbar: ^1.10.4
  sentry: ^4.0.0
  package_info: ^0.4.3+2
  intl: ^0.16.1
  intl_translation: ^0.17.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
  fonts:
   - family: Poppins
     fonts:
     - asset: assets/Poppins-BoldItalic.ttf
